/*
 * File: app/view/module/Company.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.

 */

Ext.define('Seic.view.module.Admin', {
    extend: 'Ext.ux.desktop.Module',

	id: 'admin-win',
	init: function() {
		// AQUI CRIA O ATALHO NO MENU INICIAR
        this.launcher = {
            text: 'Administração',
            iconCls:'admin-minishortcut'
        };
    },

    createWindow: function() {
        var desktop = this.app.getDesktop();
        var win = desktop.getWindow('admin-win');
        if(!win){
            win = desktop.createWindow({
                id: 'admin-win',
				iconCls: 'admin-minishortcut',
                closeAction:'hide',
                title:'Administração',
                width:850,
                height:650,
                layout:{
                        type:'fit'
                    },
                items:[
					{	xtype:'tabadmin'	}
				],
				listeners: {
					beforerender: function(){
						if(screen.height < 800){
							this.setHeight(650)
						}						
					},
					render: function(){
						//BUSCA E APLICA PERMISSÕES NESTE MÓDULO DEPOIS DE TUDO CARREGADO
						Ext.Ajax.request({
							async: false,
							waitMsg: 'Aguarde...',
							url: 'Server/getPermissoes.php',
							params: {	modulo: this.id	},
							callback: function ( options,success,response ){
								var data = Ext.decode(response.responseText);
								if( data.success ){
									//GRID USUÁRIOS
									data.permissoes.indexOf("adicionar_usuario")>-1 ? Ext.getCmp('btnAdicionarUsuario').show() : Ext.getCmp('btnAdicionarUsuario').hide();
									data.permissoes.indexOf("editar_usuario")>-1 ? (
										Ext.getCmp('btnEditarUsuario').show(),
										Ext.getCmp('gridUsuarios').on("itemdblclick", function(grid, record){
											Seic.app.getController('Admin').editarUsuarioGrid(grid, record);
										})
									): Ext.getCmp('btnEditarUsuario').hide();
									data.permissoes.indexOf("apagar_usuario")>-1 ? Ext.getCmp('btnApagarUsuario').show() : Ext.getCmp('btnApagarUsuario').hide();
									data.permissoes.indexOf("alterargrupo_usuario")>-1 ? Ext.getCmp('btnUsuarioGrupo').show() : Ext.getCmp('btnUsuarioGrupo').hide();
									data.permissoes.indexOf("liberar_usuario")>-1 ? Ext.getCmp('btnLiberarUsuario').show() : Ext.getCmp('btnLiberarUsuario').hide();
									data.permissoes.indexOf("eventos_usuario")>-1 ? Ext.getCmp('btnUsuarioEventos').show() : Ext.getCmp('btnUsuarioEventos').hide();
									//GRID EVENTOS    editarEventoGrid
									data.permissoes.indexOf("editar_evento")>-1 ? (
										Ext.getCmp('btnEditarEvento').show(),
										Ext.getCmp('gridEventos').on("itemdblclick", function(grid, record){
											Seic.app.getController('Admin').editarEventosGrid(grid, record);
										})
									): Ext.getCmp('btnEditarEvento').hide();
									data.permissoes.indexOf("adicionar_evento")>-1 ? Ext.getCmp('btnAdicionarEvento').show() : Ext.getCmp('btnAdicionarEvento').hide();
									data.permissoes.indexOf("apagar_evento")>-1 ? Ext.getCmp('btnApagarEvento').show() : Ext.getCmp('btnApagarEvento').hide();
									//GRID GRUPOS
									data.permissoes.indexOf("editar_grupo")>-1 ? (
										Ext.getCmp('btnEditarGrupo').show(),
										Ext.getCmp('gridGrupos').on("itemdblclick", function(grid, record){
											Seic.app.getController('Admin').editarGrupoGrid(grid, record);
										})
									): Ext.getCmp('btnEditarGrupo').hide();
									data.permissoes.indexOf("adicionar_grupo")>-1 ? Ext.getCmp('btnAdicionarGrupo').show() : Ext.getCmp('btnAdicionarGrupo').hide();
									data.permissoes.indexOf("apagar_grupo")>-1 ? Ext.getCmp('btnApagarGrupo').show() : Ext.getCmp('btnApagarGrupo').hide();
									data.permissoes.indexOf("acessos_grupo")>-1 ? Ext.getCmp('btnModulosGrupo').show() : Ext.getCmp('btnModulosGrupo').hide();
									data.permissoes.indexOf("liberar_grupo")>-1 ? Ext.getCmp('btnLiberarGrupo').show() : Ext.getCmp('btnLiberarGrupo').hide();
									//GRID MÓDULOS
									data.permissoes.indexOf("liberar_modulo")>-1 ? Ext.getCmp('btnLiberarModulo').show() : Ext.getCmp('btnLiberarModulo').hide();
								}
								else{
									console.log('falha');
								}
							}
						});
					}
				}
            });
        }
        return win;
    }

});