/*
 * File: app/view/module/Company.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.

 */

Ext.define('Seic.view.module.Inscritos', {
    extend: 'Ext.ux.desktop.Module',
	id: 'inscritos-win',
	init: function() {
		// AQUI CRIA O ATALHO NO MENU INICIAR
        this.launcher = {
            text: 'Inscritos',
            iconCls:'inscritos-minishortcut'
        };
    },
    createWindow: function() {
        var desktop = this.app.getDesktop();
        var win = desktop.getWindow('inscritos-win');
        if(!win){
            win = desktop.createWindow({
                id: 'inscritos-win',
				iconCls: 'inscritos-minishortcut',
                closeAction:'hide',
                title:'Inscritos',
                width:1200,
                height:780,
                layout:{
					type:'fit'
				},
				items:[
					{xtype:'modinscritos_gridinscritos'}
				],
				listeners: {
					beforerender: function(){
						if(screen.height < 800){
							this.setHeight(650)
						}						
					}
				}
            });
        }
        return win;
    }

});