/*
 * File: app/view/Desktop.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Seic.view.Desktop', {
    extend: 'Ext.ux.desktop.App',
    alias: 'widget.mydesktop',

    requires: [
        'Ext.window.MessageBox',
        'Ext.ux.desktop.ShortcutModel',
        'Seic.Settings',
		'Seic.AlterarSenha',
		'Seic.store.Wallpapers'
    ],

    init: function() {
        this.callParent();

    },
    getModules: function() {
		var modules = [];
		Ext.Ajax.request({
			async: false,
			waitMsg: 'Aguarde...',
			url: 'Server/getModules.php',
			callback: function ( options,success,response ){
				var data = Ext.decode(response.responseText);
				if( data.success ){
					Ext.each(data.modules, function(item) {
						modules.push(Ext.create(item));
					}, this);
				}
				else{
					console.log('falha');
				}

			}
		});
		return modules;
    },
    getDesktopConfig: function() {
		var me = this, ret = me.callParent();
		var atalhos = [];
		Ext.Ajax.request({
			async: false,
			waitMsg: 'Aguarde...',
			url: 'Server/getModules.php',
			callback: function ( options,success,response ){
				var data = Ext.decode(response.responseText);
				if( data.success ){
					Ext.each(data.shortcuts, function(item) {
						atalhos.push(item);
					}, this);
				}
				else{
					console.log('falha');
				}
			}
		});
		// APLICA O WALLPAPER DEFINIDO PARA O PRIMEIRO EVENTO
		var wall;
		Ext.Ajax.request({
			async: false,
			waitMsg: 'Aguarde...',
			url: 'Server/getWallpapers.php',
			callback: function ( options,success,response ){
				var data = Ext.decode(response.responseText);
				if( data.success ){
					wall = data.wallpaper;
				}
				else{
					console.log('falha');
				}

			}
		});
        return Ext.apply(ret, {
            contextMenuItems: [
                // { text: 'Alterar plano de fundo', handler: me.onSettings, scope: me }
            ],
            shortcuts: Ext.create('Ext.data.Store', {
                model: 'Ext.ux.desktop.ShortcutModel',
                data: atalhos
            }),
            wallpaper: 'resources/wallpapers/'+wall,
            wallpaperStretch: true
        });
    },
    getStartConfig: function() {
        var me = this, ret = me.callParent();
		return Ext.apply(ret, {
            title: 'Módulos disponíveis',
			alias : 'widget.iniciar',
            height: 350,
            toolConfig: {
                width: 150,
                items: [
					{	text: 'Alterar senha',
						iconCls: 'icon-access',
						handler: me.alterarSenha,
						scope: me

					},
                    '-',
                    {
                        text:'Sair do sistema',
                        iconCls:'logout',
                        handler: me.onLogout,
                        scope: me
                    }
                ]
            }
        });

    },
	alterarSenha: function(){
		var janela = new Seic.AlterarSenha({});
		janela.show();
	},
    getTaskbarConfig: function() {
        var ret = this.callParent();

        return Ext.apply(ret, {
            // quickStart: [
                // { name: 'Grid Window', iconCls: 'icon-grid', module: 'company-win' }
            // ],
            trayItems: [
				{	xtype: 'combobox',
					labelAlign: 'left',
					fieldLabel: 'EVENTO',
					id: 'combotrocarevento',
					name: 'combotrocarevento',
					padding: 3,
					queryMode: 'local',
					labelWidth: 55,
					allowBlank: true,
					editable: false,
					store: new Ext.data.JsonStore({
							proxy: {
								type: 'ajax',
								url: 'Server/listarEventosDesktop.php',
								reader: {
									type: 'json',
									root: 'resultado'
								}
							},
							fields: [
								{name:'id', 				type: 'int'},
								{name:'sigla', 				type:'string'},
								{name:'formatacao_evento', 	type:'string'},
								{name:'titulo', 			type:'string'}
							]
						}),
					// typeAhead: true,
					valueField: 'id',
					displayField: 'formatacao_evento',
					triggerAction: 'all',
					minChars: 1,
					forceSelection: false,
					loadMask: false,
					width: 380,
					listeners: {
						beforerender: function(combo){
							combo.getStore().load();
							Ext.Ajax.request({
								async: false,
								waitMsg: 'Aguarde...',
								url: 'Server/exibeTrocarEvento.php',
								callback: function ( options,success,response ){
									var data = Ext.decode(response.responseText);
									if( data.success ){
										combo.setValue(data.formatacao_evento);
									}
									else{
										combo.hide();
									}
								}
							});
						},
						select: function(combo, records){
							var store = combo.getStore();
							var index = store.find('id', combo.getValue());
							var record = store.getAt(index);
							Ext.Msg.show({
								title:   'Confirmação',
								msg:     'Deseja entrar no evento: <b>'+record.data.formatacao_evento+'</b>?',
								buttons: Ext.Msg.YESNO,
								fn: function(button){
									if(button=="yes"){
										Ext.Ajax.request({
											async: false,
											waitMsg: 'Aguarde...',
											url: 'Server/trocarEvento.php',
											params: { novo_evento: combo.getValue()	},
											callback: function ( options,success,response ){
												var data = Ext.decode(response.responseText);
												if( data.success ){
													window.location = "desktop.php";
												}
												else{

												}
											}
										});
									}
									else { 	}
								},
								animEl: 'elId',
								icon:   Ext.MessageBox.QUESTION
							});
						}
					}
				},
                { xtype: 'trayclock', flex: 1 }
            ]
        });
    },

    onLogout: function () {
        Ext.Msg.confirm('Logout', 'Tem certeza que deseja sair?', function(btn, text){
            if (btn == 'yes'){
                // process text value and close...
                    Ext.Ajax.request({
                        url: 'includes/logout.php',
                        success: function(response){
                            document.location.reload(true);
                        }
                    });

            }
        })
    },
    onSettings: function () {
        var dlg = new Seic.Settings({
            desktop: this.desktop
        });
        dlg.show();
    }

});